### ISSUE TITLE
提供12月1日至1月2日的实验室确诊数据 Provide Lab-confirmed Data from Dec 1, 2019 to Jan 2, 2020

### ISSUE THREAD

**Issue by randef1ned** [canghailan/Wuhan-2019-nCoV#1]
12月1日--1月2日数据来自
Clinical features of patients infected with 2019 novel coronavirus in Wuhan, China

1-Dec-19,1
10-Dec-19,3
15-Dec-19,2
17-Dec-19,1
18-Dec-19,1
19-Dec-19,1
20-Dec-19,5
21-Dec-19,4
22-Dec-19,3
23-Dec-19,8
24-Dec-19,1
25-Dec-19,3
26-Dec-19,2
27-Dec-19,2
31-Dec-19,3
1-Jan-20,3
2-Jan-20,1

**Comment by canghailan** [comment]
非常感谢，根据你的提示在google上搜到了[这篇](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30183-5/fulltext)。

有个疑问想请教下。

里面提到2020年1月2日的时候，确诊人数应该是41人，这个与后来卫健委提供的数据也相符。

> By Jan 2, 2020, 41 admitted hospital patients had been identified as having laboratory-confirmed 2019-nCoV infection. 

但是从图表中的数据相加是44人。不知道是那个数据的理解出现问题了。

**Comment by randef1ned** [comment]
> 非常感谢，根据你的提示在google上搜到了[这篇](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30183-5/fulltext)。
> 
> 有个疑问想请教下。
> 
> 里面提到2020年1月2日的时候，确诊人数应该是41人，这个与后来卫健委提供的数据也相符。
> 
> > By Jan 2, 2020, 41 admitted hospital patients had been identified as having laboratory-confirmed 2019-nCoV infection.
> 
> 但是从图表中的数据相加是44人。不知道是那个数据的理解出现问题了。

Mistake was caused by some unexplained reasons. 
Leaders aren't willing to read articles word by word. 
I am strongly recommended you not to use accumulated data; just as above.

**Comment by randef1ned** [comment]
还有 在dataset.py中
使用utf-8-bom或者utf-8-sig 而不是utf-8 有助于保证在Excel中的兼容性
不想再开一个新issue了

**Comment by canghailan** [comment]
> 还有 在dataset.py中
> 使用utf-8-bom或者utf-8-sig 而不是utf-8 有助于保证在Excel中的兼容性
> 不想再开一个新issue了

这个我导出xlsx格式给Excel用吧，csv打算给程序使用的，部分库对bom支持不太好。
非常感谢你的数据和解答~
