### ISSUE TITLE
二月二日数据似乎更新错误

### ISSUE THREAD

**Issue by maoxin** [canghailan/Wuhan-2019-nCoV#2]
<img width="368" alt="Screen Shot 2020-02-02 at 11 28 55 AM" src="https://user-images.githubusercontent.com/4048992/73602465-33ddf900-45af-11ea-87e3-b48e3bfc8dd6.png">

**Comment by canghailan** [comment]
已注意到腾讯新闻的源数据有问题，计划更换到头条或者丁香医生的数据源，在此之前的数据是从卫健委网站上采集的，准确性比较高，这几天的数据计划重新采集卫健委的数据更新

**Comment by maoxin** [comment]
谢谢！

**Comment by canghailan** [comment]
已切换到今日头条数据接口，正在观察数据的准确性。
之前的数据也在从卫健委的网站上采集中，预计1-2天可更新完毕。
