### ISSUE TITLE
Wrong number of total cases for France on April 17th

### ISSUE THREAD

**Issue by roysaad** [canghailan/Wuhan-2019-nCoV#21]
The total cases in the CSV file for France (FR) is too high.

**Comment by canghailan** [comment]
Repair based on WHO data

[Situation report - 88](https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200417-sitrep-88-covid-191b6cccd94f8b4f219377bff55719a6ed.pdf?sfvrsn=ebe78315_6)
