### ISSUE TITLE
Different columns order after Apr 27 2020 in Wuhan-2019-nCoV.csv

### ISSUE THREAD

**Issue by roysaad** [canghailan/Wuhan-2019-nCoV#22]
The columns order of **Wuhan-2019-nCoV.csv** is
date,**countryCode,country**,province,provinceCode,city,cityCode,confirmed,suspected,cured,dead
after Apr 27 2020 while it was
date,**country,countryCode**,province,provinceCode,city,cityCode,confirmed,suspected,cured,dead

**Comment by ecator** [comment]
I noticed the same problem, so my service that used this data source couldn't work now :cry:

求作者大大赶快解决 😭

**Comment by ecator** [comment]
It seems that this problem has been fixed at 25b449587f4e155abe27b3f2d2c31f0af2dd98b3
