### ISSUE TITLE
更新日期最近三日的数据有问题

### ISSUE THREAD

**Issue by haowu97** [canghailan/Wuhan-2019-nCoV#3]
我发现这个数据总是更新日期最近三日的数据有问题，麻烦楼主检查一下是不是程序不对？感谢

**Comment by canghailan** [comment]
已注意到腾讯新闻的源数据有问题，计划更换到头条或者丁香医生的数据源，在此之前的数据是从卫健委网站上采集的，准确性比较高，这几天的数据计划重新采集卫健委的数据更新

**Comment by lovechang1986** [comment]
是的，近几天的数据似乎不对。

**Comment by canghailan** [comment]
已切换到今日头条数据接口，正在观察数据的准确性。
之前的数据也在从卫健委的网站上采集中，预计1-2天可更新完毕。
