### ISSUE TITLE
数据接口只有Chrome能访问

### ISSUE THREAD

**Issue by wjbgis** [canghailan/Wuhan-2019-nCoV#6]
https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json
这两个数据接口只有chrome浏览器访问得到，试了下edge,firefox，都无法访问

**Comment by canghailan** [comment]
我测试是可用的（直接地址栏打开、fetch、axios）。这个地址国内访问可能有问题，与你用户代理的配置有关？

我的版本是
操作系统 Mac
浏览器版本 Firefox 73、Edge 80
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48
```

**Comment by wjbgis** [comment]
感谢大佬提供的数据接口，基于您提供的数据，我做了一份geojson每日累计数据，以方便于地图展示，空间分析等。
https://github.com/wjbgis/2019-nCov-geojson-data
