### ISSUE TITLE
2/18 的数据有点问题，似乎一部分是2/19的

### ISSUE THREAD

**Issue by wenpinghtl** [canghailan/Wuhan-2019-nCoV#7]
数据获取时间： 2/19 10:40
-----------
date: "2020-02-18"
country: "中国"
countryCode: "CN"
province: ""
provinceCode: ""
city: ""
cityCode: ""
confirmed: 74279
suspected: 5248
cured: 14387
dead: 2006

----------

date: "2020-02-19"
country: "中国"
countryCode: "CN"
province: ""
provinceCode: ""
city: ""
cityCode: ""
confirmed: 74279
suspected: 5248
cured: 14390
dead: 2006

**Comment by wenpinghtl** [comment]
该时间段的 头条的数据
![toutiao](https://user-images.githubusercontent.com/31976258/74797174-da472f80-530d-11ea-894b-b89e40914f82.jpg)

**Comment by canghailan** [comment]
![image](https://user-images.githubusercontent.com/1196864/74797872-23e04c00-5307-11ea-8519-3f8d9ab5000c.png)
![image](https://user-images.githubusercontent.com/1196864/74797910-43777480-5307-11ea-8e0d-b4464ebeb8f6.png)
![image](https://user-images.githubusercontent.com/1196864/74798066-b41e9100-5307-11ea-8b14-f0189e4657b8.png)
![image](https://user-images.githubusercontent.com/1196864/74797989-79b4f400-5307-11ea-8ac3-6527cc376ed5.png)

确认了下，头条数据接口返回的就是如此。这是头条的数据更新机制造成的，数据会根据卫健委的数据修正一次，导致数据不一致。

**Comment by wenpinghtl** [comment]
好的，谢谢！
结论： 头条接口返回数据问题。 -> Close
