### ISSUE TITLE
部分省份city列中有‘未公布来源’

### ISSUE THREAD

**Issue by xuestrange** [canghailan/Wuhan-2019-nCoV#9]
首先，非常感谢作者分享数据。
我查看了今日头条网站上的数据发现，确实有些省份存在‘未公布来源’，比如：河南；但是有些省份并没有‘未公布来源’，比如：福建，但是下载了您的数据中却发现福建省有未公布来源。

**Comment by canghailan** [comment]
数据在不停变化，目前每天的数据是晚上23:57那一刻的头条数据，第二天不会再进行更新。我也监控下未公布来源数据。
